apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.vishuofflinetts'
version = '0.1.0'

android {
  namespace 'expo.modules.vishuofflinetts'
  compileSdkVersion rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.20.0'
}
